// labels.js — display names for every taxonomy value, in both languages.
//
// The Bangla here is written to be what someone would actually say — "ছিনতাই",
// not a formal translation of "mugging" — because a form that reads like a
// government circular does not get filled in.
//
// NEEDS A NATIVE REVIEW PASS before launch. I am confident about the common
// terms (ছিনতাই, চাঁদাবাজি, জিডি, মাস্তানি) and less so about the legal and
// infrastructure vocabulary. Anything wrong here is visible to every visitor,
// so it is worth an hour of someone's time.

export const labels = {
  bn: {
    // categories
    mugging: 'ছিনতাই',
    theft: 'চুরি',
    chadabaji: 'চাঁদাবাজি',
    land_grabbing: 'জমি দখল',
    hooliganism: 'মাস্তানি',
    drugs_weapons: 'মাদক ও অস্ত্র',
    fraud_impersonation: 'প্রতারণা ও ভুয়া পরিচয়',
    transport_danger: 'বিপজ্জনক যান চলাচল',
    police_misconduct: 'পুলিশি অনিয়ম',
    harassment: 'হয়রানি ও উত্ত্যক্ত',
    assault: 'হামলা',
    abduction: 'অপহরণ',
    // mugging
    snatching: 'টানা-হেঁচড়া',
    armed_robbery: 'অস্ত্র দেখিয়ে ডাকাতি',
    vehicle_based: 'গাড়ি/সিএনজি থেকে',
    hijacking: 'গাড়ি ছিনতাই',
    // theft
    pickpocketing: 'পকেটমার',
    motorcycle_theft: 'মোটরসাইকেল চুরি',
    vehicle_theft: 'গাড়ি চুরি',
    burglary: 'বাসায় চুরি',
    shop_robbery: 'দোকানে ডাকাতি',
    // chadabaji
    shop_business: 'দোকান/ব্যবসা',
    construction_site: 'নির্মাণকাজ',
    transport: 'পরিবহন',
    festival_event: 'উৎসব/অনুষ্ঠান',
    land: 'জমি',
    illegal_toll: 'অবৈধ টোল/চাঁদা তোলা',
    protection_racket: 'নিরাপত্তার নামে চাঁদা',
    // land grabbing
    eviction_threat: 'উচ্ছেদের হুমকি',
    forced_occupation: 'জোর করে দখল',
    fake_documents: 'ভুয়া দলিল',
    boundary_encroachment: 'সীমানা দখল',
    // hooliganism
    street_fight: 'মারামারি',
    intimidation_display: 'শক্তি প্রদর্শন/ভয় দেখানো',
    vandalism: 'ভাঙচুর',
    forced_shutdown: 'জোর করে দোকান বন্ধ',
    // drugs and weapons
    dealing_spot: 'মাদক বেচাকেনার স্পট',
    open_drug_use: 'প্রকাশ্যে মাদক সেবন',
    arms_display: 'প্রকাশ্যে অস্ত্র',
    gambling_den: 'জুয়ার আসর',
    // fraud
    fake_police: 'ভুয়া পুলিশ/ডিবি',
    fake_checkpoint: 'ভুয়া চেকপোস্ট',
    coerced_mobile_banking: 'জোর করে বিকাশ/নগদ',
    fake_collection: 'ভুয়া নামে টাকা তোলা',
    // transport danger
    reckless_driving: 'বেপরোয়া গাড়ি চালানো',
    street_racing: 'রাস্তায় রেসিং',
    unlicensed_driver: 'লাইসেন্সবিহীন/অপ্রাপ্তবয়স্ক চালক',
    dangerous_overtaking: 'বিপজ্জনক ওভারটেক',
    // police misconduct
    gd_refused: 'জিডি নেয়নি',
    bribe_to_file: 'মামলা নিতে ঘুষ',
    bribe_to_drop: 'মামলা তুলতে ঘুষ',
    complicity_with_group: 'সন্ত্রাসীদের সঙ্গে যোগসাজশ',
    direct_extortion: 'সরাসরি চাঁদা দাবি',
    custodial_abuse: 'হেফাজতে নির্যাতন',
    harassment_by_police: 'পুলিশি হয়রানি',
    illegal_checkpoint: 'অবৈধ চেকপোস্টে টাকা আদায়',
    // harassment
    street_harassment: 'রাস্তায় উত্ত্যক্ত',
    transport_groping: 'গণপরিবহনে গায়ে হাত',
    stalking: 'পিছু নেওয়া',
    threats: 'হুমকি',
    // assault
    physical_assault: 'মারধর',
    weapon_assault: 'অস্ত্র দিয়ে আঘাত',
    acid_attack: 'অ্যাসিড নিক্ষেপ',
    // abduction
    kidnapping: 'মুক্তিপণের জন্য অপহরণ',
    attempted_abduction: 'অপহরণের চেষ্টা',
    trafficking_suspicion: 'পাচারের সন্দেহ',
    // hazards
    lighting: 'বাতি ও অন্ধকার',
    road_surface: 'রাস্তা ও ড্রেন',
    footpath: 'ফুটপাত',
    construction: 'নির্মাণকাজ',
    electrical: 'বৈদ্যুতিক ঝুঁকি',
    crossing: 'পারাপার',
    obstruction: 'রাস্তা আটকানো',
    streetlight_broken: 'নষ্ট স্ট্রিটলাইট',
    streetlight_absent: 'বাতি নেই',
    dark_stretch: 'অন্ধকার রাস্তা',
    open_manhole: 'খোলা ম্যানহোল',
    open_drain: 'খোলা ড্রেন',
    broken_road: 'ভাঙা রাস্তা',
    waterlogging: 'জলাবদ্ধতা',
    footpath_blocked: 'ফুটপাত বন্ধ',
    footpath_encroached: 'ফুটপাত দখল',
    footpath_broken: 'ভাঙা ফুটপাত',
    unsafe_construction: 'অনিরাপদ নির্মাণকাজ',
    debris_on_road: 'রাস্তায় নির্মাণসামগ্রী',
    unmarked_excavation: 'চিহ্ন ছাড়া খোঁড়াখুঁড়ি',
    dangling_wires: 'ঝুলন্ত তার',
    exposed_transformer: 'খোলা ট্রান্সফরমার',
    no_crossing: 'পারাপারের ব্যবস্থা নেই',
    broken_signal: 'নষ্ট সিগন্যাল',
    accident_blackspot: 'দুর্ঘটনাপ্রবণ জায়গা',
    abandoned_vehicle: 'পরিত্যক্ত গাড়ি',
    blocking_parking: 'রাস্তা আটকে পার্কিং',
    // time
    morning: 'সকাল', afternoon: 'দুপুর', evening: 'সন্ধ্যা',
    night: 'রাত', unknown: 'জানি না',
    // why not reported
    would_ask_for_money: 'টাকা চাইত',
    connected_to_group: 'ওরা ওদেরই লোক',
    would_tell_them_i_complained: 'ওদের বলে দিত যে আমি অভিযোগ করেছি',
    nothing_would_happen: 'কিছুই হতো না',
    afraid_of_retaliation: 'প্রতিশোধের ভয়',
    did_not_know_how: 'কীভাবে করতে হয় জানতাম না',
    ashamed_or_blamed: 'লোকে আমাকেই দোষ দিত',
    other: 'অন্যান্য',
    // outcomes
    gd_filed: 'জিডি হয়েছে',
    no_action: 'কোনো ব্যবস্থা নেয়নি',
    money_demanded: 'টাকা চেয়েছে',
    // amounts
    under_1k: '১,০০০ টাকার কম', '1k_5k': '১,০০০–৫,০০০',
    '5k_25k': '৫,০০০–২৫,০০০', '25k_100k': '২৫,০০০–১,০০,০০০',
    over_100k: '১,০০,০০০ টাকার বেশি',
    // method
    one: 'একজন', two: 'দুজন', three_to_five: 'তিন–পাঁচজন', more: 'আরও বেশি',
    none: 'কিছু ছিল না', motorcycle: 'মোটরসাইকেল', cng: 'সিএনজি',
    car: 'গাড়ি', bicycle: 'সাইকেল',
    knife: 'ছুরি/চাকু', firearm: 'আগ্নেয়াস্ত্র', blunt: 'লাঠি/রড', acid: 'অ্যাসিড',
    from_behind: 'পিছন থেকে', blocked_path: 'পথ আটকে',
    posed_as_official: 'পুলিশ/কর্মকর্তা সেজে', followed: 'পিছু নিয়ে',
    group_surrounded: 'দল বেঁধে ঘিরে',
  },

  en: {
    mugging: 'Mugging', theft: 'Theft', chadabaji: 'Chadabaji (extortion)',
    land_grabbing: 'Land grabbing', hooliganism: 'Hooliganism (mastani)',
    drugs_weapons: 'Drugs and weapons', fraud_impersonation: 'Fraud and impersonation',
    transport_danger: 'Dangerous driving', police_misconduct: 'Police misconduct',
    harassment: 'Harassment', assault: 'Assault', abduction: 'Abduction',
    snatching: 'Snatching', armed_robbery: 'Armed robbery',
    vehicle_based: 'From a vehicle', hijacking: 'Vehicle hijacking',
    pickpocketing: 'Pickpocketing', motorcycle_theft: 'Motorcycle theft',
    vehicle_theft: 'Vehicle theft', burglary: 'Burglary', shop_robbery: 'Shop robbery',
    shop_business: 'Shop / business', construction_site: 'Construction site',
    transport: 'Transport', festival_event: 'Festival / event', land: 'Land',
    illegal_toll: 'Illegal toll collection', protection_racket: 'Protection racket',
    eviction_threat: 'Eviction threat', forced_occupation: 'Forced occupation',
    fake_documents: 'Forged documents', boundary_encroachment: 'Boundary encroachment',
    street_fight: 'Street fight', intimidation_display: 'Show of force',
    vandalism: 'Vandalism', forced_shutdown: 'Forced shop closure',
    dealing_spot: 'Dealing spot', open_drug_use: 'Open drug use',
    arms_display: 'Weapons openly carried', gambling_den: 'Gambling den',
    fake_police: 'Fake police / DB', fake_checkpoint: 'Fake checkpoint',
    coerced_mobile_banking: 'Coerced bKash / Nagad transfer',
    fake_collection: 'Collecting money under a false name',
    reckless_driving: 'Reckless driving', street_racing: 'Street racing',
    unlicensed_driver: 'Unlicensed or underage driver',
    dangerous_overtaking: 'Dangerous overtaking',
    gd_refused: 'GD refused', bribe_to_file: 'Bribe to file',
    bribe_to_drop: 'Bribe to drop', complicity_with_group: 'Complicity with a group',
    direct_extortion: 'Direct extortion', custodial_abuse: 'Custodial abuse',
    harassment_by_police: 'Harassment by police',
    illegal_checkpoint: 'Money taken at an illegal checkpoint',
    street_harassment: 'Street harassment', transport_groping: 'Groping in transport',
    stalking: 'Being followed', threats: 'Threats',
    physical_assault: 'Beating', weapon_assault: 'Attacked with a weapon',
    acid_attack: 'Acid attack',
    kidnapping: 'Kidnapping for ransom', attempted_abduction: 'Attempted abduction',
    trafficking_suspicion: 'Suspected trafficking',
    lighting: 'Lighting and darkness', road_surface: 'Road and drains',
    footpath: 'Footpath', construction: 'Construction', electrical: 'Electrical hazard',
    crossing: 'Crossing', obstruction: 'Blocked road',
    streetlight_broken: 'Broken streetlight', streetlight_absent: 'No streetlight',
    dark_stretch: 'Dark stretch', open_manhole: 'Open manhole', open_drain: 'Open drain',
    broken_road: 'Broken road', waterlogging: 'Waterlogging',
    footpath_blocked: 'Footpath blocked', footpath_encroached: 'Footpath encroached',
    footpath_broken: 'Footpath broken', unsafe_construction: 'Unsafe construction',
    debris_on_road: 'Debris on the road', unmarked_excavation: 'Unmarked excavation',
    dangling_wires: 'Dangling wires', exposed_transformer: 'Exposed transformer',
    no_crossing: 'No crossing', broken_signal: 'Broken signal',
    accident_blackspot: 'Accident blackspot', abandoned_vehicle: 'Abandoned vehicle',
    blocking_parking: 'Parking blocking the road',
    morning: 'Morning', afternoon: 'Afternoon', evening: 'Evening',
    night: 'Night', unknown: 'Not sure',
    would_ask_for_money: 'They would ask for money',
    connected_to_group: 'They are connected to the group',
    would_tell_them_i_complained: 'They would tell them I complained',
    nothing_would_happen: 'Nothing would happen anyway',
    afraid_of_retaliation: 'I was afraid of retaliation',
    did_not_know_how: 'I did not know how',
    ashamed_or_blamed: 'I would have been blamed',
    other: 'Other',
    gd_filed: 'GD filed', no_action: 'No action', money_demanded: 'Money demanded',
    under_1k: 'Under 1,000', '1k_5k': '1,000–5,000', '5k_25k': '5,000–25,000',
    '25k_100k': '25,000–1,00,000', over_100k: 'Over 1,00,000',
    one: 'One', two: 'Two', three_to_five: 'Three to five', more: 'More',
    none: 'None', motorcycle: 'Motorcycle', cng: 'CNG', car: 'Car', bicycle: 'Bicycle',
    knife: 'Knife', firearm: 'Firearm', blunt: 'Stick or rod', acid: 'Acid',
    from_behind: 'From behind', blocked_path: 'Blocked the path',
    posed_as_official: 'Posed as police or an official', followed: 'Followed first',
    group_surrounded: 'Surrounded by a group',
  },
};
