<script>
  import { ui, restoreLang, setLang } from '$lib/state.svelte.js';
  import { page } from '$app/state';
  import { strings } from '$lib/i18n.js';
  import { onMount } from 'svelte';
  let { children } = $props();
  const t = $derived(strings[ui.lang]);
  const onSubmitPage = $derived(page.url?.pathname?.startsWith('/submit'));

  // If the published data was generated by the demo seeder, say so on every
  // page. Synthetic numbers that look official are worse than no numbers.
  // 'demo' synthetic numbers · 'beta' real but empty · 'live' real reports.
  // An empty map with no explanation is indistinguishable from a broken one,
  // so beta gets its own banner rather than silence.
  let mode = $state(null);
  const demo = $derived(mode === 'demo');
  onMount(async () => {
    restoreLang();
    try {
      const m = await (await fetch('/data/meta.json')).json();
      mode = m.mode ?? (m.demo ? 'demo' : 'live');
    } catch { /* meta is optional */ }
  });

  // The document language has to follow the toggle. It was hardcoded to "bn",
  // so a screen reader read the English pages with a Bangla voice, and
  // translation tools were told the wrong thing.
  $effect(() => {
    if (typeof document !== 'undefined') document.documentElement.lang = ui.lang;
  });
</script>

<!-- Seven tab stops stood between a keyboard or screen-reader user and the
     content on every page. -->
<a class="skip" href="#main">{t.skip_link}</a>

<header>
  <a class="brand" href="/">{t.site}<span class="tld">.site</span></a>
  <!-- Reporting is the one action this site needs from a visitor, so it is a
       button, not the third grey link of five. The rest are references. -->
  <nav>
    <a href="/">{t.nav_map}</a>
    <a href="/thana/">{t.nav_areas}</a>
    <a href="/gd/">{t.nav_help}</a>
    <a href="/methodology/">{t.nav_method}</a>
  </nav>
  <!-- Offering "Report" while you are already filling the report form is
       noise; on that page the button becomes the way back to the map. -->
  {#if onSubmitPage}
    <a class="report ghost" href="/">{t.nav_map}</a>
  {:else}
    <a class="report" href="/submit/">{t.nav_submit}</a>
  {/if}
  <button class="lang" onclick={() => setLang(ui.lang === 'bn' ? 'en' : 'bn')}>
    {ui.lang === 'bn' ? 'English' : 'বাংলা'}
  </button>
</header>

{#if mode === 'demo'}
  <div class="demo">
    {ui.lang === 'bn'
      ? 'ডেমো: এই পাতার সব সংখ্যা কৃত্রিমভাবে তৈরি। কোনোটিই প্রকৃত ঘটনা নয়।'
      : 'DEMO. Every number on this site is synthetic. None of it describes a real incident.'}
  </div>
{:else if mode === 'beta'}
  <div class="beta">{t.beta_banner}</div>
{/if}

<main id="main" tabindex="-1">{@render children()}</main>

<footer>
  <!-- Three things belong on every page, not only on the methodology page a
       visitor will never open: what this is not, what we keep, and the numbers
       to call when the answer is not a website. -->
  <p class="disclaim">{t.not_authority}</p>
  <nav class="flinks">
    <a href="/methodology/">{t.nav_method}</a>
    <a href="/gd/">{t.nav_help}</a>
    {#if !onSubmitPage}<a href="/submit/">{t.nav_submit}</a>{/if}
  </nav>
  <p class="fine">
    {ui.lang === 'bn'
      ? 'আমরা আইপি, লোকেশন বা কোনো ব্যক্তিগত তথ্য সংরক্ষণ করি না। কোনো অ্যাকাউন্ট নেই।'
      : 'We store no IP, no location, and no personal data. There are no accounts.'}
  </p>
  <p class="emergency">{t.foot_emergency}</p>
</footer>

<style>
  /* Type.
   *
   * Two faces, both self-hosted, both OFL-1.1 (licences ship beside the
   * files). A font CDN would see every visitor of a police-misconduct site,
   * which is the one thing this project will not allow, so `font-src: 'self'`
   * in the CSP makes that enforceable rather than promised.
   *
   * Hind Siliguri for Bangla: it is what Bangladeshi readers actually see on
   * the web, so the page reads native rather than translated. Inter for Latin
   * and for numerals. The unicode-range on Inter is what keeps a Bangla reader
   * from downloading a Latin face they will barely see, and vice versa.
   *
   * Weights are 400/600/700 only. There is no 300 and no 500 on purpose: every
   * extra weight is another 70 KB over a connection that may be terrible, and
   * three weights is enough to build a hierarchy with.
   *
   * That hierarchy has to come from weight and size, NOT from capitals.
   * Bangla has no uppercase, so an all-caps display style reads as emphasis in
   * English and as nothing at all in Bangla. Do not add text-transform here. */
  @font-face {
    font-family: 'Inter'; font-style: normal; font-weight: 400;
    font-display: swap; src: url('/fonts/ui/inter-latin-400.woff2') format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+2000-206F,
                   U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215;
  }
  @font-face {
    font-family: 'Inter'; font-style: normal; font-weight: 600;
    font-display: swap; src: url('/fonts/ui/inter-latin-600.woff2') format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+2000-206F,
                   U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215;
  }
  @font-face {
    font-family: 'Inter'; font-style: normal; font-weight: 700;
    font-display: swap; src: url('/fonts/ui/inter-latin-700.woff2') format('woff2');
    unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+2000-206F,
                   U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215;
  }
  /* U+200C/200D are ZWNJ and ZWJ: Bangla conjunct control characters. Leave
   * them out and a hasant sequence silently falls back to another face
   * mid-word. U+25CC is the dotted circle a broken cluster renders into, and
   * it should come from the same font as the vowel sign sitting on it. */
  @font-face {
    font-family: 'Hind Siliguri'; font-style: normal; font-weight: 400;
    font-display: swap; src: url('/fonts/ui/hind-siliguri-bengali-400.woff2') format('woff2');
    unicode-range: U+0964-0965, U+0980-09FF, U+200C-200D, U+20B9, U+25CC, U+A8F1;
  }
  @font-face {
    font-family: 'Hind Siliguri'; font-style: normal; font-weight: 600;
    font-display: swap; src: url('/fonts/ui/hind-siliguri-bengali-600.woff2') format('woff2');
    unicode-range: U+0964-0965, U+0980-09FF, U+200C-200D, U+20B9, U+25CC, U+A8F1;
  }
  @font-face {
    font-family: 'Hind Siliguri'; font-style: normal; font-weight: 700;
    font-display: swap; src: url('/fonts/ui/hind-siliguri-bengali-700.woff2') format('woff2');
    unicode-range: U+0964-0965, U+0980-09FF, U+200C-200D, U+20B9, U+25CC, U+A8F1;
  }

  :global(:root) {
    --bg: #0f1113; --panel: #171a1d; --line: #2a2f34;
    --ink: #e9edf1; --dim: #98a2ad; --accent: #d98b3a; --warn: #c9564b;
    color-scheme: dark;

    /* Inter first so Latin and digits take it; Bangla falls through to Hind
     * Siliguri by unicode-range. The system fallbacks are what a visitor sees
     * for the ~200 ms before the files land, and Nirmala UI is the one that
     * ships with Windows. */
    --font: 'Inter', 'Hind Siliguri', system-ui, 'Nirmala UI',
            'Noto Sans Bengali', sans-serif;

    /* Hind Siliguri sits small on its em and its line box is tall, so Bangla
     * set at the same nominal size as Latin looks smaller and more cramped
     * than it is. Both numbers are corrections for that, not preferences. */
    --lh: 1.7;
    --step--1: .875rem;
    --step-0: 1rem;
    --step-1: 1.125rem;
    --step-2: 1.375rem;
    --step-3: 1.75rem;
    --step-4: clamp(2rem, 1.4rem + 2.4vw, 3rem);
  }
  :global(*) { box-sizing: border-box; }
  :global(body) {
    margin: 0; background: var(--bg); color: var(--ink);
    font-family: var(--font);
    font-size: var(--step-0);
    line-height: var(--lh);
    /* Hind Siliguri's default figures are fine, but Inter's are slightly
     * narrow next to Bangla digits. Tabular figures also stop counts in the
     * panel jittering as they update. */
    font-variant-numeric: tabular-nums;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
  }
  /* Headings tighten their line box: --lh is set for running Bangla text and
   * looks loose the moment the type gets big. */
  :global(h1) { font-size: var(--step-3); line-height: 1.25; font-weight: 700; margin: 0 0 .5rem; letter-spacing: -.01em; }
  :global(h2) { font-size: var(--step-2); line-height: 1.3; font-weight: 600; margin: 1.8rem 0 .5rem; }
  :global(h3) { font-size: var(--step-1); line-height: 1.35; font-weight: 600; margin: 1.4rem 0 .4rem; }
  :global(small), :global(.fine) { font-size: var(--step--1); }
  :global(a) { color: inherit; }
  header {
    display: flex; gap: 1rem; align-items: center; flex-wrap: wrap;
    padding: .7rem 1rem; border-bottom: 1px solid var(--line); background: var(--panel);
    position: sticky; top: 0; z-index: 10;
  }
  .skip {
    position: absolute; left: .5rem; top: -3rem; z-index: 20;
    background: var(--accent); color: #17130a; font-weight: 700;
    padding: .5rem .9rem; border-radius: 0 0 8px 8px; text-decoration: none;
    transition: top .12s;
  }
  .skip:focus { top: 0; }
  main:focus { outline: none; }
  .brand { font-weight: 700; text-decoration: none; font-size: 1.15rem; }
  .tld { color: var(--dim); font-weight: 400; }
  nav { display: flex; gap: .9rem; flex-wrap: wrap; font-size: .9rem; }
  nav a { color: var(--dim); text-decoration: none; }
  nav a:hover { color: var(--ink); }
  .report.ghost { background: none; border: 1px solid var(--line); color: var(--ink); }
  .report {
    margin-left: auto; background: var(--accent); color: #17130a;
    text-decoration: none; font-weight: 700; font-size: .9rem;
    border-radius: 999px; padding: .35rem .9rem; white-space: nowrap;
  }
  .lang {
    background: none; border: 1px solid var(--line);
    color: var(--ink); border-radius: 999px; padding: .25rem .8rem; cursor: pointer;
  }
  /* On a phone the header wraps to two rows; keep the report button on the
     first one with the brand, where a thumb finds it. */
  @media (max-width: 560px) {
    header { gap: .5rem .8rem; }
    nav { order: 3; width: 100%; gap: .8rem; }
    .report { margin-left: auto; }
  }
  main { max-width: 1000px; margin: 0 auto; padding: 1rem; }
  footer {
    border-top: 1px solid var(--line); margin-top: 3rem; padding: 1.2rem 1rem;
    color: var(--dim); font-size: .85rem; text-align: center;
  }
  .fine { font-size: .8rem; }
  .disclaim { max-width: 46rem; margin: 0 auto .8rem; color: var(--dim); }
  .flinks { display: flex; gap: 1.1rem; justify-content: center; margin-bottom: .8rem; }
  .flinks a { color: var(--dim); text-decoration: none; }
  .flinks a:hover { color: var(--ink); }
  .emergency { color: var(--ink); font-size: .82rem; margin-top: 1rem; opacity: .85; }
  .demo {
    background: var(--warn); color: #140908; text-align: center;
    padding: .45rem 1rem; font-size: .85rem; font-weight: 600;
  }
  /* Beta is a statement of fact, not a warning: amber, not red. */
  .beta {
    background: #2a2216; border-bottom: 1px solid var(--accent);
    color: var(--ink); text-align: center;
    padding: .45rem 1rem; font-size: .85rem;
  }
</style>
