<script>
  import { ui } from '$lib/state.svelte.js';
  import { strings } from '$lib/i18n.js';
  import { onMount } from 'svelte';
  let { children } = $props();
  const t = $derived(strings[ui.lang]);

  // If the published data was generated by the demo seeder, say so on every
  // page. Synthetic numbers that look official are worse than no numbers.
  let demo = $state(false);
  onMount(async () => {
    try { demo = (await (await fetch('/data/meta.json')).json()).demo === true; }
    catch { /* meta is optional */ }
  });
</script>

<header>
  <a class="brand" href="/">{t.site}<span class="tld">.site</span></a>
  <!-- Reporting is the one action this site needs from a visitor, so it is a
       button, not the third grey link of five. The rest are references. -->
  <nav>
    <a href="/">{t.nav_map}</a>
    <a href="/thana/">{t.nav_areas}</a>
    <a href="/gd/">{t.nav_help}</a>
    <a href="/methodology/">{t.nav_method}</a>
  </nav>
  <a class="report" href="/submit/">{t.nav_submit}</a>
  <button class="lang" onclick={() => (ui.lang = ui.lang === 'bn' ? 'en' : 'bn')}>
    {ui.lang === 'bn' ? 'English' : 'বাংলা'}
  </button>
</header>

{#if demo}
  <div class="demo">
    {ui.lang === 'bn'
      ? 'ডেমো: এই পাতার সব সংখ্যা কৃত্রিমভাবে তৈরি। কোনোটিই প্রকৃত ঘটনা নয়।'
      : 'DEMO. Every number on this site is synthetic. None of it describes a real incident.'}
  </div>
{/if}

<main>{@render children()}</main>

<footer>
  <!-- Three things belong on every page, not only on the methodology page a
       visitor will never open: what this is not, what we keep, and the numbers
       to call when the answer is not a website. -->
  <p class="disclaim">{t.not_authority}</p>
  <nav class="flinks">
    <a href="/methodology/">{t.nav_method}</a>
    <a href="/gd/">{t.nav_help}</a>
    <a href="/submit/">{t.nav_submit}</a>
  </nav>
  <p class="fine">
    {ui.lang === 'bn'
      ? 'আমরা আইপি, লোকেশন বা কোনো ব্যক্তিগত তথ্য সংরক্ষণ করি না। কোনো অ্যাকাউন্ট নেই।'
      : 'We store no IP, no location, and no personal data. There are no accounts.'}
  </p>
  <p class="emergency">{t.foot_emergency}</p>
</footer>

<style>
  :global(:root) {
    --bg: #0f1113; --panel: #171a1d; --line: #2a2f34;
    --ink: #e9edf1; --dim: #98a2ad; --accent: #d98b3a; --warn: #c9564b;
    color-scheme: dark;
  }
  :global(*) { box-sizing: border-box; }
  :global(body) {
    margin: 0; background: var(--bg); color: var(--ink);
    font: 16px/1.55 system-ui, 'Noto Sans Bengali', 'Nirmala UI', sans-serif;
  }
  :global(h1) { font-size: 1.5rem; margin: 0 0 .4rem; }
  :global(h2) { font-size: 1.1rem; margin: 1.6rem 0 .5rem; }
  :global(a) { color: inherit; }
  header {
    display: flex; gap: 1rem; align-items: center; flex-wrap: wrap;
    padding: .7rem 1rem; border-bottom: 1px solid var(--line); background: var(--panel);
    position: sticky; top: 0; z-index: 10;
  }
  .brand { font-weight: 700; text-decoration: none; font-size: 1.15rem; }
  .tld { color: var(--dim); font-weight: 400; }
  nav { display: flex; gap: .9rem; flex-wrap: wrap; font-size: .9rem; }
  nav a { color: var(--dim); text-decoration: none; }
  nav a:hover { color: var(--ink); }
  .report {
    margin-left: auto; background: var(--accent); color: #17130a;
    text-decoration: none; font-weight: 700; font-size: .9rem;
    border-radius: 999px; padding: .35rem .9rem; white-space: nowrap;
  }
  .lang {
    background: none; border: 1px solid var(--line);
    color: var(--ink); border-radius: 999px; padding: .25rem .8rem; cursor: pointer;
  }
  /* On a phone the header wraps to two rows; keep the report button on the
     first one with the brand, where a thumb finds it. */
  @media (max-width: 560px) {
    header { gap: .5rem .8rem; }
    nav { order: 3; width: 100%; gap: .8rem; }
    .report { margin-left: auto; }
  }
  main { max-width: 1000px; margin: 0 auto; padding: 1rem; }
  footer {
    border-top: 1px solid var(--line); margin-top: 3rem; padding: 1.2rem 1rem;
    color: var(--dim); font-size: .85rem; text-align: center;
  }
  .fine { font-size: .8rem; }
  .disclaim { max-width: 46rem; margin: 0 auto .8rem; color: var(--dim); }
  .flinks { display: flex; gap: 1.1rem; justify-content: center; margin-bottom: .8rem; }
  .flinks a { color: var(--dim); text-decoration: none; }
  .flinks a:hover { color: var(--ink); }
  .emergency { color: var(--ink); font-size: .82rem; margin-top: 1rem; opacity: .85; }
  .demo {
    background: var(--warn); color: #140908; text-align: center;
    padding: .45rem 1rem; font-size: .85rem; font-weight: 600;
  }
</style>
